services:
  db:
    container_name: mysql
    image: mysql:9.5
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - c:/temp/DB:/var/lib/mysql
  php:
    container_name: php
    build:
      context: .
    ports:
      - "9999:80"
    volumes:
      - ./app/src:/var/www/html
    env_file: .env
    depends_on:
      - db
